### ISSUE TITLE
Mouse: add support for multiple buttons pressed at the same time

### ISSUE THREAD

**Issue by davcri** [crystal-bit/input-overlay#6]
See https://github.com/crystal-bit/input-overlay/blob/main/addons/input-overlay/overlay-widget/overlay-widget.gd#L16

**Comment by lucashilles** [comment]
Can i work on this feature?

**Comment by davcri** [comment]
Sure thing! Thanks for the internet in the project

**Comment by lucashilles** [comment]
PR open.
![image](https://github.com/crystal-bit/input-overlay/assets/11667069/6eb31a21-fb53-4277-ae7c-0db691c4e7d7)
